version: 2
jobs:
  build_sdk:
    working_directory: ~/gs2-cpp-sdk
    docker:
      - image: gs2io/gs2-cpp-sdk_build
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          CIRCLE_ARTIFACTS: /tmp/test-results
    steps:
      - checkout
      -
        run:
          name: テストをチェックアウト
          command: |
            cd ..
            git clone -b ${CIRCLE_BRANCH} git@github.com:gs2io/gs2-cpp-test.git || git clone -b develop git@github.com:gs2io/gs2-cpp-test.git
      -
        run:
          name: CMake
          command: |
            cd ../cmake-build
            cmake -DGS2_COCOS2DX_PREBUILD=False -DGS2_SDK_PREBUILT=False ..
      -
        run:
          name: ターゲットを決定
          command: |
            cd ../cmake-build
            ../gs2-cpp-test/.circleci/targets.sh ../gs2-cpp-test/.circleci/filter_gs2-cpp-sdk.sh > targets
            cat targets
      -
        run:
          name: SDK のビルド
          command: |
            cd ../cmake-build
            make gs2-cpp-sdk-all
      -
        persist_to_workspace:
          root: /root
          paths:
            - gs2-cpp-test
            - cmake-build/lib
            - cmake-build/targets

  build_test:
    working_directory: ~/gs2-cpp-sdk
    docker:
      - image: gs2io/gs2-cpp-sdk_build
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          CIRCLE_ARTIFACTS: /tmp/test-results
    parallelism: 4
    steps:
      - checkout
      -
        attach_workspace:
          at: /root
      -
        run:
          name: CMake
          command: |
            cd ../cmake-build
            cmake -DGS2_COCOS2DX_PREBUILD=False -DGS2_SDK_PREBUILT=True ..
      -
        run:
          name: テストをビルド
          command: |
            cd ../cmake-build
            circleci tests split < targets | ../gs2-cpp-test/.circleci/build.sh
      -
        persist_to_workspace:
          root: /root
          paths:
            - cmake-build/bin

  run_test:
    working_directory: ~/cmake-build
    docker:
      - image: gs2io/gs2-cpp-sdk_build
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          CIRCLE_ARTIFACTS: /tmp/test-results
    parallelism: 4
    steps:
      -
        attach_workspace:
          at: /root
      -
        run:
          name: テストを実行
          command: |
            mkdir -p bin
            cd bin
            find . -executable -type f | circleci tests split | xargs -I{} /bin/bash -c 'mkdir -p /root/.config/{}; {}'


workflows:
  version: 2
  build_and_test:
    jobs:
      - build_sdk
      -
        build_test:
          requires:
            - build_sdk
      -
        run_test:
          requires:
            - build_test
