version: 2
jobs:
  build:
    working_directory: ~/gs2-cpp-sdk
    docker:
      - image: gs2io/gs2-cpp-sdk_build
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          CIRCLE_ARTIFACTS: /tmp/test-results
    steps:
      - checkout
      -
        run:
          name: テストをチェックアウト
          command: |
            cd ..
            git clone -b ${CIRCLE_BRANCH} git@github.com:gs2io/gs2-cpp-test.git || git clone -b develop git@github.com:gs2io/gs2-cpp-test.git
      -
        run:
          name: CMake
          command: |
            cd ../cmake-build
            cmake -DGS2_COCOS2DX_PREBUILD=False -DGS2_SDK_PREBUILT=False ..
      -
        run:
          name: SDK パッケージの作成
          command: |
            cd ../cmake-build
            make gs2-cpp-sdk-package
      -
        store_artifacts:
          path: /root/gs2-cpp-sdk/src/gs2-unreal-engine-sdk_YYYY.MM.R.zip
          destination: packages/gs2-unreal-engine-sdk_YYYY.MM.R.zip
